#cloud-config
autoinstall:
  version: 1
  early-commands:
    - swapoff -a
  locale: en_US.UTF-8
  keyboard:
    layout: jp
  timezone: Asia/Tokyo
  identity:
    realname: thanh_tt
    username: thanh_tt
    hostname: DTMPC-001
    password: "$6$HNsGefkmZ6sgIF4S$E9tFAXjxa9wMfytOn7GiYBvGnzb8xrHyei0hYM2ahddlqlW58J/FfQuX7mocw7/Kkyk2gBsIoAlr/W0lPtu441"
  storage:
    config:
      - type: disk
        id: disk-ssd
        match:
          serial: "YOUR SSD SERIAL HERE"
        ptable: gpt
        preserve: false
        wipe: superblock-recursive
      - type: partition
        id: partition-efi
        device: disk-ssd
        size: 1024M
        flag: boot
        grub_device: true
      - type: format
        id: format-efi
        fstype: vfat
        volume: partition-efi
      - type: mount
        id: mount-efi
        device: format-efi
        path: /boot/efi
      - type: partition
        id: partition-root
        device: disk-ssd
        size: 200G
      - type: format
        id: format-root
        fstype: ext4
        volume: partition-root
      - type: mount
        id: mount-root
        device: format-root
        path: /
      - type: partition
        id: partition-home
        device: disk-ssd
        size: 630G
      - type: dm_crypt
        id: luks-home
        volume: partition-home
        preserve: false
        key: "YOUR SSD PASSWORD HERE"
      - type: format
        id: format-home
        fstype: ext4
        volume: luks-home
      - type: mount
        id: mount-home
        device: format-home
        path: /home
  ssh:
    install-server: true
    allow-pw: true